import React from 'react';
import './history.css'

const History = () => {
    return (
        <div className="history">
            <h1>History of France</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga repellat, adipisci dolor perspiciatis tenetur necessitatibus fugiat illo dolores omnis voluptatibus doloribus pariatur repellendus repudiandae aspernatur? Temporibus quisquam maxime doloribus perspiciatis, sit omnis est? Voluptas, quisquam tempora libero, sequi ratione a, asperiores fuga animi commodi rem dolorum incidunt et temporibus fugiat voluptatem itaque veniam perferendis tenetur. In quisquam obcaecati recusandae eos? Cupiditate qui officiis omnis veniam vero. Id labore vitae, cum, saepe unde magni tenetur doloribus harum deleniti voluptatem mollitia illo recusandae accusantium libero velit reiciendis blanditiis, eius rem fugiat eveniet aperiam dolores et corrupti. At, eum! Nesciunt rem est distinctio ipsum eos quaerat officia aliquam exercitationem id cumque architecto, esse amet consectetur facilis doloremque magnam voluptates cum aliquid nemo deleniti beatae necessitatibus tenetur quibusdam. Quisquam dolorem, temporibus deleniti quae voluptatum ex exercitationem odit id. Assumenda, alias. Dolore mollitia voluptatibus saepe illo cum! Ex dolorum nostrum deserunt asperiores, iusto odio dolorem voluptatem nisi ipsa accusamus numquam voluptates porro doloremque dignissimos laboriosam tempora quia vero tempore temporibus ullam. Magnam quos dicta laborum ad laboriosam incidunt voluptatum quasi tempore dolor facere magni obcaecati error, eligendi adipisci vitae sit pariatur beatae, eius aliquid maiores corporis reprehenderit at! Debitis distinctio in incidunt explicabo placeat ut?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi non voluptates, corrupti voluptate saepe beatae libero debitis eum est accusamus natus inventore nam, blanditiis ratione quam facilis deleniti, tempora facere ut dolorum veniam minima alias autem! Veniam exercitationem dolor maiores, incidunt aliquid iste debitis, quas voluptates nostrum suscipit delectus reiciendis quisquam hic provident ab itaque unde harum ipsam cupiditate sit, quasi corporis quo numquam atque. Mollitia soluta voluptates, officiis ratione voluptas, nemo quia numquam ut eum reprehenderit enim nostrum omnis quas id repellendus? Consequuntur, repudiandae aspernatur consectetur magni inventore fugiat ipsum accusamus pariatur quam voluptatibus repellat doloribus mollitia, voluptatum minus perspiciatis tenetur explicabo. Harum inventore odit, culpa similique enim voluptates veritatis nam expedita sequi quo? Nulla veritatis cupiditate ut repellendus iusto, optio quam, doloremque omnis nobis incidunt sunt sint magni enim id soluta reprehenderit tenetur repellat assumenda eos explicabo facere magnam atque. Possimus, ullam aperiam architecto alias eius laboriosam eveniet illo delectus est cumque quisquam ut ipsum sunt dolor perferendis magnam enim molestias hic. Quidem unde quam ipsam hic, praesentium rerum corporis voluptates. Nostrum debitis eum placeat, laudantium dignissimos inventore a, cum quas repellat id quibusdam deserunt at quos voluptates tenetur natus vero facilis maiores perspiciatis unde! Omnis, iusto eos.</p>
        </div>
    )
}

export default History
